# https://docs.docker.com/compose/compose-file
# Docker-compose Tricks and Best Practices
# https://medium.com/factualopinions/docker-compose-tricks-and-best-practices-5e7e43eba8eb
# https://dgraph.io/docs/master/deploy/config/ (envars)

version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  # Dgraph Zero controls the Dgraph cluster, assigns servers to a group, and re-balances data between server groups.
  dgraph-zero:
    image: dgraph/dgraph:v22.0.2
    container_name: dgraph-zero
    networks:
      - shared-network
    environment:
      - DGRAPH_ZERO_MY=dgraph-zero:5080
      - DGRAPH_ZERO_ENABLE_SENTRY=false
    command: dgraph zero
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure

  # Dgraph Alpha hosts predicates and indexes.
  # Predicates are either the properties associated with a node or the relationship between two nodes.
  # Indexes are the tokenizers that can be associated with the predicates to enable filtering using appropriate functions.
  dgraph-alpha:
    container_name: dgraph-alpha
    networks:
      - shared-network
    image: dgraph/dgraph:v22.0.2
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    depends_on:
      - dgraph-zero
    restart: on-failure
    environment:
      - DGRAPH_ALPHA_MY=dgraph-alpha:7080
      - DGRAPH_ALPHA_LRU_MB=2048
      - DGRAPH_ALPHA_ZERO=dgraph-zero:5080
      - DGRAPH_ALPHA_WHITELIST=0.0.0.0/0
      - DGRAPH_ALPHA_ENABLE_SENTRY=false
    command: dgraph alpha --vmodule=server=3

  # Ratel serves the UI to run queries, mutations & altering schema.
  dgraph-ratel:
    image: dgraph/dgraph:v22.0.2
    container_name: dgraph-ratel
    networks:
      - shared-network
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel
volumes:
  dgraph:
